### PR TITLE
Update view_helpers.rb

### PR DESCRIPTION
**Pull request by appleboy**

### CODE REVIEW

**Comment by appleboy** [comment]
LGTM

**Comment by appleboy** [comment]
LGTM

**Comment by appleboy** [comment]
LGTM

**Comment by appleboy** [comment]
LGTM

**Review by appleboy46 — APPROVED** [review]

**Review by appleboy46 — CHANGES_REQUESTED** [review]
XD

**Review by appleboy46 — CHANGES_REQUESTED** [review]
DDDDDDD

**Review by yisin — CHANGES_REQUESTED** [review]
XD

**Review by yisin — APPROVED** [review]

**Pull request closed without merging**
